### PR TITLE
build `tcl` / `tk` inside `magic-vlsi`

### PR DESCRIPTION
**Pull request by gnawhleinad**
As mentioned in https://github.com/RTimothyEdwards/magic/issues/280#issuecomment-1883451857, the `magic-vlsi` Formula isn't working for me... I'll continue to investigate.

I started _this_ pull request to take some of the content in https://github.com/Homebrew/homebrew-core/blob/master/Formula/t/tcl-tk.rb and move it to _here_. Primarily, I'm hoping to make this formula be compatible with a simultaneous installation of `core/tcl-tk`.

### CODE REVIEW

**Comment by shaunplee** [comment]
OK, I think I figured out the incompatibililty with `core/tcl-tk`. The problem is the `--mandir=#{man}` argument in `tcl_tk_args`. After removing this argument from a local copy of your version of the formula, homebrew successfully builds and links `magic-vlsi`.

My guess is that the `--mandir=#{man}` argument causes the man pages for tcl/tk to end up in the `man` directory for `magic-vlsi` (because that's what `#{man}` means in this `magic-vlsi` formula) and then homebrew tries to link those tcl/tk man pages, which collide with the man pages that are already there.

I think I somehow committed my suggested edit to your fork.

**Comment by gnawhleinad** [comment]
Unfortunately, I'm still failing to build `magic`. I'm not completely sure why but the `tk` build is not able to find the `X11` dependencies from my `XQuartz` installation...

I'm still failing the build with:

```
clang -c -I/private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../unix -I/private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../generic -I/private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../bitmaps -I/opt/X11/include -O2 -pipe  -arch arm64e   -Wall -Wpointer-arith -fno-common -DBUILD_tk -I/private/tmp/magic-vlsi--tcl-20240110-70984-ek9dn1/tcl8.6.13/generic -I/private/tmp/magic-vlsi--tcl-20240110-70984-ek9dn1/tcl8.6.13/unix -DPACKAGE_NAME=\"tk\" -DPACKAGE_TARNAME=\"tk\" -DPACKAGE_VERSION=\"8.6\" -DPACKAGE_STRING=\"tk\ 8.6\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DHAVE_PTHREAD_ATTR_SETSTACKSIZE=1 -DHAVE_PTHREAD_ATFORK=1 -DTCL_THREADS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DMAC_OSX_TCL=1 -DHAVE_COREFOUNDATION=1 -DTCL_CFG_DO64BIT=1 -DHAVE_CAST_TO_UNION=1 -DTCL_SHLIB_EXT=\".dylib\" -DNDEBUG=1 -DTCL_CFG_OPTIMIZED=1 -DTCL_WIDE_INT_IS_LONG=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_INTPTR_T=1 -DHAVE_UINTPTR_T=1 -DHAVE_PW_GECOS=1 -DHAVE_AVAILABILITYMACROS_H=1 -DHAVE_WEAK_IMPORT=1 -D_DARWIN_C_SOURCE=1 -DXKEYCODETOKEYSYM_IS_DEPRECATED=1        -DUSE_TCL_STUBS -fno-lto /private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../generic/tkStubLib.c
In file included from /private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../generic/tkStubLib.c:14:
In file included from /private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../generic/tkInt.h:19:
In file included from /private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../generic/tkPort.h:21:
/private/tmp/magic-vlsi--tk-20240110-70984-uqrgu9/tk8.6.13/unix/../generic/tk.h:99:13: fatal error: 'X11/Xlib.h' file not found
#   include <X11/Xlib.h>
            ^~~~~~~~~~~~
1 error generated.
make: *** [tkStubLib.o] Error 1
```

It's very odd because the `configure` logs explicitly show:

```
checking for Tcl configuration... found /opt/homebrew/Cellar/magic-vlsi/8.3.456/tcl-tk/lib/tclConfig.sh
checking for existence of /opt/homebrew/Cellar/magic-vlsi/8.3.456/tcl-tk/lib/tclConfig.sh... loading
checking for tclsh... /usr/bin/tclsh8.5
checking for tclsh in Tcl build directory... /opt/homebrew/Cellar/magic-vlsi/8.3.456/tcl-tk/lib/tclsh
...
checking for X... libraries /opt/X11/lib, headers /opt/X11/include
checking for main in -lXbsd... no
checking whether to use xft... no
checking for X11/XKBlib.h... yes
```

> My guess is that the `--mandir=#{man}` argument causes the man pages for tcl/tk to end up in the `man` directory for `magic-vlsi` (because that's what `#{man}` means in this `magic-vlsi` formula) and then homebrew tries to link those tcl/tk man pages, which collide with the man pages that are already there.

:sparkles:, nice sleuthing!

> I think I somehow committed my suggested edit to your fork.

😆 , this is a GitHub functionality - see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests.

**Comment by shaunplee** [comment]
I wonder if the `xquartz` thing is a red herring.

The formula should probably also have a `depends_on “libx11”` line.

**Comment by gnawhleinad** [comment]
> The formula should probably also have a `depends_on “libx11”` line.

🤔 , maybe!

Interestingly, I found https://github.com/pbk20191/homebrew-trunk/blob/6a002d9298903b4599c816fe843bb34249e36d72/Formula/magic.rb#L40 while trying to work backwards from https://github.com/macports/macports-ports/blob/2b3db2e5447ee45b23b800dcb82282b8a97f299c/science/magic/Portfile#L67C21-L67C32.

**Comment by gnawhleinad** [comment]
Once we have a working Formula especially from a clean action runner (see https://github.com/shaunplee/homebrew-asic/pull/2), we should create a pull request against https://github.com/RTimothyEdwards/magic/blob/master/INSTALL_MacOS.md with the updated:tm: and validated options.

**Comment by shaunplee** [comment]
> > The formula should probably also have a `depends_on “libx11”` line.
> 
> 🤔 , maybe!
> 
> Interestingly, I found https://github.com/pbk20191/homebrew-trunk/blob/6a002d9298903b4599c816fe843bb34249e36d72/Formula/magic.rb#L40 while trying to work backwards from https://github.com/macports/macports-ports/blob/2b3db2e5447ee45b23b800dcb82282b8a97f299c/science/magic/Portfile#L67C21-L67C32.

Very interesting. Maybe I should just use that formula instead! 😂

**Review by shaunplee — APPROVED** [review]

**Review by shaunplee — APPROVED** [review]

**Review by shaunplee — APPROVED** [review]

**Review by shaunplee — APPROVED** [review]

**Comment by shaunplee** [comment]
@gnawhleinad Is this working now on your machine?

**Comment by gnawhleinad** [comment]
> @gnawhleinad Is this working now on your machine?

No... I'm still trying to figure out why my `tk` isn't building...

**Comment by shaunplee** [comment]
> > @gnawhleinad Is this working now on your machine?
> 
> No... I'm still trying to figure out why my `tk` isn't building...

Will you try out the `tcl-tk-with-x` formula in this tap?

**Comment by gnawhleinad** [comment]
> Will you try out the `tcl-tk-with-x` formula in this tap?

Unfortunately, it's the same error.

```
brew install shaunplee/asic/tcl-tk-with-x
==> Fetching shaunplee/asic/tcl-tk-with-x
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.13/tk8.6.13-src.tar.gz
Already downloaded: /Users/gnawhleinad/Library/Caches/Homebrew/downloads/bef9117e92c7475cbd16e59c8cddb35e8f38e15c1534582673ad9749e65fffb3--tk8.6.13-src.tar.gz
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.13/tcl8.6.13-src.tar.gz
Already downloaded: /Users/gnawhleinad/Library/Caches/Homebrew/downloads/bce3c72eeccfba5e3812dc3f01f625538d082965901a088f9076fb9fd34dcbb3--tcl8.6.13-src.tar.gz
==> Installing tcl-tk-with-x from shaunplee/asic
==> ./configure --enable-threads --enable-64bit
==> make
==> make install
==> make install-private-headers
==> ./configure --enable-threads --enable-64bit --with-tcl=/opt/homebrew/Cellar/tcl-tk-with-x/8.6.13_5/lib --with-x
==> make
Last 15 lines from /Users/gnawhleinad/Library/Logs/Homebrew/tcl-tk-with-x/06.make:
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [tkAtom.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make: *** [tkBusy.o] Error 1
make: *** [tkBind.o] Error 1
make: *** [tk3d.o] Error 1
1 error generated.
make: *** [ttkStubLib.o] Error 1
1 error generated.
1 error generated.
make: *** [tkStubLib.o] Error 1
make: *** [tkBitmap.o] Error 1
```

```
...
/private/tmp/tcl-tk-with-x--tk-20240111-48967-a0rl9m/tk8.6.13/unix/../generic/tk.h:99:13: fatal error: 'X11/Xlib.h' file not found
#   include <X11/Xlib.h>
            ^~~~~~~~~~~~
1 error generated.
make: *** [tkArgv.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [tkAtom.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make: *** [tkBusy.o] Error 1
make: *** [tkBind.o] Error 1
make: *** [tk3d.o] Error 1
1 error generated.
make: *** [ttkStubLib.o] Error 1
1 error generated.
1 error generated.
make: *** [tkStubLib.o] Error 1
make: *** [tkBitmap.o] Error 1
```

**Comment by gnawhleinad** [comment]
Are you using an ARM-based macOS system?

I wonder if the core difference is that you've installed MacPorts on your system (https://github.com/RTimothyEdwards/magic/issues/280#issuecomment-1876545662)...

**Comment by shaunplee** [comment]
Yes, I'm using an ARM-based macOS system. I've also now uninstalled MacPorts, but there could be remnants lurking.

Does the `tcl-tk-x11` formula used by the other magic-vlsi formula build for you?

https://github.com/sethrfore/homebrew-r-srf/blob/master/tcl-tk-x11.rb

**Comment by gnawhleinad** [comment]
> Does the `tcl-tk-x11` formula used by the other magic-vlsi formula build for you?

Unfortunately, this fails too...

```
/private/tmp/tcl-tk-x11--tk-20240111-89462-nsmk7z/tk8.6.13/unix/../generic/tk.h:99:13: fatal error: 'X11/Xlib.h' file not found
#   include <X11/Xlib.h>
            ^~~~~~~~~~~~
1 error generated.
1 error generated.
make: *** [tkAtom.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [tkStubLib.o] Error 1
1 error generated.
1 error generated.
make: *** [tkBusy.o] Error 1
make: *** [tkArgv.o] Error 1
1 error generated.
1 error generated.
make: *** [tk3d.o] Error 1
make: *** [ttkStubLib.o] Error 1
1 error generated.
make: *** [tkBind.o] Error 1
1 error generated.
make: *** [tkBitmap.o] Error 1

HOMEBREW_VERSION: 4.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 3 days ago
Core tap JSON: 11 Jan 05:30 UTC
Core cask tap JSON: 11 Jan 05:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UC7RwGykQZ/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /opt/homebrew/opt/libxau/lib/pkgconfig:/opt/homebrew/opt/libxdmcp/lib/pkgconfig:/opt/homebrew/opt/libxcb/lib/pkgconfig:/opt/homebrew/opt/libx11/lib/pkgconfig:/opt/homebrew/opt/xorgproto/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Cellar/tcl-tk-x11/8.6.13/bin:/opt/homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by shaunplee** [comment]
Maybe you’ve already found this answer, buy have you done: `xcode-select --install` on your current machine?

https://apple.stackexchange.com/questions/240659/x11-xlib-h-file-not-found

**Comment by gnawhleinad** [comment]
> Maybe you’ve already found this answer, buy have you done: `xcode-select --install` on your current machine?
> 
> https://apple.stackexchange.com/questions/240659/x11-xlib-h-file-not-found

😢 , unfortunately, I have tried that...

`magic` is compiling in the runner (https://github.com/shaunplee/homebrew-asic/actions/runs/7492711963/job/20396839904) so all signs point to something weird / broken on my machine. I'll report back but in the mean time... if this is working for you, I think you should pursue updating https://github.com/RTimothyEdwards/magic/blob/master/INSTALL_MacOS.md.

**Comment by shaunplee** [comment]
@gnawhleinad Thanks for your help with this. I learned a bunch!

**Pull request merged**
